sudo: required
language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

services:
 - docker

script:
 - docker build -t twitchax/podcastssyndicate:latest .

after_success:
 - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
 - docker push twitchax/podcastssyndicate:$TRAVIS_COMMIT
